/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saket
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientTreatmentWorkRequest patientTreatmentWorkRequest;

    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, PatientTreatmentWorkRequest patientTreatmentWorkRequest) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patientTreatmentWorkRequest = patientTreatmentWorkRequest;
        lblValue.setText(enterprise.getName());
        btnRequestTest.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestTest = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblValue = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblLabType = new javax.swing.JLabel();
        txtLabType = new javax.swing.JTextField();
        lblRequestLabTest = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequestTest.setBackground(new java.awt.Color(0, 0, 0));
        btnRequestTest.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnRequestTest.setForeground(new java.awt.Color(153, 255, 204));
        btnRequestTest.setText("Request Test");
        btnRequestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTestActionPerformed(evt);
            }
        });
        add(btnRequestTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 140, 30));

        lblMessage.setBackground(new java.awt.Color(0, 0, 0));
        lblMessage.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(153, 255, 204));
        lblMessage.setText("Message:");
        add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 70, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 130, 30));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 255, 204));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        lblValue.setBackground(new java.awt.Color(0, 0, 0));
        lblValue.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblValue.setForeground(new java.awt.Color(153, 255, 204));
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, 20));

        lblEnterprise.setBackground(new java.awt.Color(0, 0, 0));
        lblEnterprise.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblEnterprise.setForeground(new java.awt.Color(153, 255, 204));
        lblEnterprise.setText("Enterprise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 20));

        lblLabType.setBackground(new java.awt.Color(0, 0, 0));
        lblLabType.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblLabType.setForeground(new java.awt.Color(153, 255, 204));
        lblLabType.setText("Lab Type:");
        add(lblLabType, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 150, 80, -1));
        add(txtLabType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 130, 30));

        lblRequestLabTest.setBackground(new java.awt.Color(0, 0, 0));
        lblRequestLabTest.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblRequestLabTest.setForeground(new java.awt.Color(153, 255, 204));
        lblRequestLabTest.setText("REQUEST LAB TEST");
        add(lblRequestLabTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTestActionPerformed

        String labType = txtLabType.getText().trim();
        String message = txtMessage.getText().trim();

        if (labType.equals("")) {
            JOptionPane.showMessageDialog(null, "Lap type is mandatory!");
            return;
        }
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Message is mandatory");
            return;
        }

        patientTreatmentWorkRequest.setLabTestMessage(message);
        patientTreatmentWorkRequest.setSender(userAccount);
        patientTreatmentWorkRequest.setStatus("SentToLab");
        patientTreatmentWorkRequest.setReceiver(null);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizations()) {
            if (organization instanceof LabOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
            userAccount.getWorkQueue().getWorkRequests().add(patientTreatmentWorkRequest);
            JOptionPane.showMessageDialog(null, "Lab request sent");
            txtMessage.setText("");
            txtLabType.setText("");
            btnRequestTest.setEnabled(false);
        }

    }//GEN-LAST:event_btnRequestTestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestTest;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblLabType;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblRequestLabTest;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField txtLabType;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
