/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabAssistantRole;

import Business.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    PatientTreatmentWorkRequest patientTreatmentWorkRequest;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer,
            PatientTreatmentWorkRequest patientTreatmentWorkRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patientTreatmentWorkRequest = patientTreatmentWorkRequest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmitResult = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblLabResultTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        btnSubmitResult.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmitResult.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnSubmitResult.setForeground(new java.awt.Color(153, 255, 204));
        btnSubmitResult.setText("Submit");
        btnSubmitResult.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitResultActionPerformed(evt);
            }
        });
        add(btnSubmitResult);
        btnSubmitResult.setBounds(270, 250, 140, 36);

        lblResult.setBackground(new java.awt.Color(0, 0, 0));
        lblResult.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblResult.setForeground(new java.awt.Color(153, 255, 204));
        lblResult.setText("Result :");
        add(lblResult);
        lblResult.setBounds(140, 130, 70, 17);
        add(txtResult);
        txtResult.setBounds(210, 120, 280, 100);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 255, 204));
        btnBack.setText("<< Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 11, 55, 23);

        lblLabResultTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblLabResultTitle.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblLabResultTitle.setForeground(new java.awt.Color(153, 255, 204));
        lblLabResultTitle.setText("LAB RESULTS");
        add(lblLabResultTitle);
        lblLabResultTitle.setBounds(270, 30, 130, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabAssistantWorkAreaJPanel labassistant = (LabAssistantWorkAreaJPanel) component;
        labassistant.populateTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }// GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitResultActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSubmitResultActionPerformed
        String labResult;
        labResult = txtResult.getText().trim();
        if (labResult.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid data !");
            return;
        } else {
            int dialogResult;
            dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                patientTreatmentWorkRequest.setLabResult(labResult);
                patientTreatmentWorkRequest.setStatus("Lab test is Completed");
                JOptionPane.showMessageDialog(null, "Result submitted successfully");
                txtResult.setText("");
                btnSubmitResult.setEnabled(false);
            }

        }

    }// GEN-LAST:event_btnSubmitResultActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitResult;
    private javax.swing.JLabel lblLabResultTitle;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
