/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ngoResourceCoordinator;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ngoDeploymentSpecialistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ngoVolunteerRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author revan
 */
public class ResourceCoordinatorProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResourceCoordinatorProcessWorkRequestJPanel
     */
    private JPanel jPanel;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ngoVolunteerRequest NgoVolunteerRequest;

    public ResourceCoordinatorProcessWorkRequestJPanel(JPanel jPanel, UserAccount userAccount, ngoVolunteerRequest volunteerRequest, Enterprise enterprise) {
        initComponents();

        this.jPanel = jPanel;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.NgoVolunteerRequest = volunteerRequest;
        txtAmount.setText(String.valueOf(NgoVolunteerRequest.getVolunteerRequested()));
        txtRegion.setText(NgoVolunteerRequest.getRegion());
        txtPopulation.setText(String.valueOf(NgoVolunteerRequest.getPopulation()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSecretery = new javax.swing.JLabel();
        btnTransferRequest = new javax.swing.JButton();
        lblLocation = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtRegion = new javax.swing.JTextField();
        txtPopulation = new javax.swing.JTextField();
        lblPopulation = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(153, 255, 204));

        lblSecretery.setBackground(new java.awt.Color(0, 0, 0));
        lblSecretery.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblSecretery.setForeground(new java.awt.Color(153, 255, 204));
        lblSecretery.setText("PROCESS PENDING NGO RESOURCE COORDINATOR REQUESTS");

        btnTransferRequest.setBackground(new java.awt.Color(0, 0, 0));
        btnTransferRequest.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnTransferRequest.setForeground(new java.awt.Color(153, 255, 204));
        btnTransferRequest.setText("Forward Request To Deployment Specialist");
        btnTransferRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferRequestActionPerformed(evt);
            }
        });

        lblLocation.setBackground(new java.awt.Color(0, 0, 0));
        lblLocation.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(153, 255, 204));
        lblLocation.setText("Location :");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 255, 204));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtRegion.setEnabled(false);

        txtPopulation.setEnabled(false);

        lblPopulation.setBackground(new java.awt.Color(0, 0, 0));
        lblPopulation.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblPopulation.setForeground(new java.awt.Color(153, 255, 204));
        lblPopulation.setText("Population :");

        txtAmount.setEnabled(false);

        lblAmount.setBackground(new java.awt.Color(0, 0, 0));
        lblAmount.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(153, 255, 204));
        lblAmount.setText("Number of Volunteers:");

        lblMessage.setBackground(new java.awt.Color(0, 0, 0));
        lblMessage.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(153, 255, 204));
        lblMessage.setText("Message :");

        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        btnReject.setBackground(new java.awt.Color(0, 0, 0));
        btnReject.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnReject.setForeground(new java.awt.Color(153, 255, 204));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMessage)
                                            .addComponent(lblPopulation))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(645, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblSecretery)
                                .addContainerGap(617, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTransferRequest)
                        .addGap(85, 85, 85)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(485, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnReject, btnTransferRequest});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecretery))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLocation)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPopulation)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount)
                    .addComponent(lblMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransferRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(425, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnReject, btnTransferRequest});

    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferRequestActionPerformed
        // TODO add your handling code here:

        String msg = txtMessage.getText();
        if (msg.equals("")) {
            JOptionPane.showMessageDialog(null, "Kindly enter a message!");
            return;
        }
        else{
        NgoVolunteerRequest.setMessage(msg);
        
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to proceed?");
            
         if (dialogResult == JOptionPane.YES_OPTION) {
        NgoVolunteerRequest.setSender(userAccount);
        NgoVolunteerRequest.setStatus("Sent to Deployment Specialist");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizations()) {
            if (organization instanceof ngoDeploymentSpecialistOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequests().add(NgoVolunteerRequest);
            userAccount.getWorkQueue().getWorkRequests().add(NgoVolunteerRequest);
        }
        JOptionPane.showMessageDialog(null, "Requested to Deployment Specialist is completed!!!");
        txtMessage.setText("");
            btnReject.setEnabled(false);
            btnTransferRequest.setEnabled(false);
        }

        txtMessage.setText("");
        }
    }//GEN-LAST:event_btnTransferRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ResourceCoordinatorWorkAreaJPanel swjp = (ResourceCoordinatorWorkAreaJPanel) component;
        swjp.populateTable();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        String message = txtMessage.getText();
         if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Kindly enter a message!");
            return;
        } else {
        NgoVolunteerRequest.setMessage(message);
        
         int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                NgoVolunteerRequest.setStatus("Rejected");
                txtMessage.setText("");
            btnReject.setEnabled(false);
            btnTransferRequest.setEnabled(false);
            }
            txtMessage.setText("");
         }
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnTransferRequest;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPopulation;
    private javax.swing.JLabel lblSecretery;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPopulation;
    private javax.swing.JTextField txtRegion;
    // End of variables declaration//GEN-END:variables
}
